### ISSUE TITLE
Missing build require on six

### ISSUE THREAD

**Issue by nijel** [youknowone/wirerope#10]
The package fails to install because it requires six to build:

```
$ pip install wirerope
Collecting wirerope
  Downloading wirerope-0.4.1.tar.gz (8.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/wirerope/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i0d9u7_j/wirerope/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i0d9u7_j/wirerope/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ao4qbv48
         cwd: /tmp/pip-install-i0d9u7_j/wirerope/
    Complete output (39 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i0d9u7_j/wirerope/setup.py", line 6, in <module>
        setuptools.setup()
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/tmp/wirerope/lib/python3.8/site-packages/_virtualenv.py", line 21, in parse_config_files
        result = old_parse_config_files(self, *args, **kwargs)
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/dist.py", line 701, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/tmp/wirerope/lib/python3.8/site-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-install-i0d9u7_j/wirerope/wirerope/__init__.py", line 5, in <module>
        from .wire import Wire
      File "/tmp/pip-install-i0d9u7_j/wirerope/wirerope/wire.py", line 5, in <module>
        from .callable import Descriptor
      File "/tmp/pip-install-i0d9u7_j/wirerope/wirerope/callable.py", line 4, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Either it should specify it according to PEP 508 or avoid the six dependency at build time (for example by not importing the code). Or maybe it's time to drop Python 2 support and six usage...

**Comment by youknowone** [comment]
I am sorry to make this happened. I released a new version a minute ago.

**Comment by nijel** [comment]
This is probably a side effect of fewer modules requiring six because it started to break our CI just now...
