### ISSUE TITLE
installation failed with setuptools postfix release

### ISSUE THREAD

**Issue by drjackild** [youknowone/wirerope#8]
Hi!

I've got an errror when trying to install Sanic-Restplus (which uses your package). 

```
       command: /usr/local/anaconda3/envs/project/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kt/63f1vlpj55b89jhx87jvg6pm0000gn/T/pip-resolver-mvppy43f/wirerope/setup.py'"'"'; __file__='"'"'/private/var/folders/kt/63f1vlpj55b89jhx87jvg6pm0000gn/T/pip-resolver-mvppy43f/wirerope/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kt/63f1vlpj55b89jhx87jvg6pm0000gn/T/pip-pip-egg-info-i1fq66rq
           cwd: /private/var/folders/kt/63f1vlpj55b89jhx87jvg6pm0000gn/T/pip-resolver-mvppy43f/wirerope/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/kt/63f1vlpj55b89jhx87jvg6pm0000gn/T/pip-resolver-mvppy43f/wirerope/setup.py", line 3, in <module>
          assert tuple(map(int, setuptools.__version__.split('.'))) >= (39, 2, 0), \
      ValueError: invalid literal for int() with base 10: 'post20200622'
```

Looks like the assert in setup.py always except integer, but there are a few versions of setuptools with postfix (like `setuptools-47.3.1.post20200622`). After upgrade setuptools I resolve this issue, but I think it's better to avoid these problems. The version of my setuptools was correct, but can't be parsed anyway

Thank you!

**Comment by youknowone** [comment]
Thanks! I will fix it soon.

**Comment by jyggen** [comment]
I'm running into a similar issue when installing `wirerope` (or rather `ring`) using pip through [Pants](https://pantsbuild.org/):

```bash
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_h/fr5ctz890wb5h87sgsvbdr5h0000gn/T/process-executionuTO3si/.tmp/pip-download-v1heqzg0/wirerope_8e7e469bacad47419c57647ad8aa5798/setup.py", line 3, in <module>
        assert tuple(map(int, setuptools.__version__.split('.')[:3])) >= (39, 2, 0), \
    ValueError: invalid literal for int() with base 10: '0+3acb925dd708430aeaf197ea53ac8a752f7c1863'
```
